spring.application.name=Insurance_Management_Service

spring.datasource.url=jdbc:mysql://localhost:3306/Insurance_Management?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=2436

spring.jpa.hibernate.ddl-auto=update