spring.application.name=Driver_service

spring.datasource.url=jdbc:mysql://localhost:3306/driver?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=2436

spring.jpa.hibernate.ddl-auto=update